sonar.projectKey=dozens-api
sonar.projectName=Dozenz API
sonar.sources=apps/api/src
sonar.rust.cargo.manifestPaths=apps/api/Cargo.toml
sonar.rust.lcov.reportPaths=apps/api/lcov.info
sonar.sourceEncoding=UTF-8
