 services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: dev
    working_dir: /dozens/apps/api
    ports:
      - 3000:3000
    volumes:
      - ..:/dozens
    command: ["sleep", "infinity"]
