[package]
name = "api"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "api"
path = "src/bin/api.rs"

[dependencies]
anyhow = "1.0.104"
async-trait = "0.1.92"
aws-config = "1"
aws-sdk-cloudwatchlogs = "1.136.0"
aws-sdk-cognitoidentityprovider = "1.136.0"
axum = "0.8.9"
fake = "5.1.0"
jiff = "0.2.37"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.20"
toasty = { version = "0.10.0", features = ["dynamodb", "jiff", "migration", "postgresql"] }
toasty-cli = "0.10.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
uuid = { version = "1", features = ["v7"] }
validator = { version = "0.21.0", features = ["derive"] }

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"], default-features = false }
aws-sdk-cloudwatchlogs = "1.153.0"

[lints.rust]
warnings = "deny"
